import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from "next";
import Header from "@/components/Header";
// import Sidebar from "@/components/Sidebar";
import '@/Assets/Style/style.scss';
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" data-theme="light" >

        <head>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
        </head>
        <body>
          <Header />
          {/* <Sidebar /> */}
          <main >
            {children}
          </main>
        </body>
      </html>
    </>
  );
}
